scan_matcher: 
  ros__parameters: 
    global_frame_id: 'map'
    robot_frame_id: 'base_link'
    registration_method: 'NDT'
    ndt_resolution: 2.5
    ndt_num_threads: 3
    gicp_corr_dist_threshold: 5.0
    trans_for_mapupdate: 2.0
    vg_size_for_input: 0.2
    vg_size_for_map: 0.05
    use_min_max_filter: true
    scan_min_range: 5.0
    scan_max_range: 200.0
    scan_period: 0.2
    map_publish_period: 1000.0
    num_targeted_cloud: 30
    set_initial_pose: true
    initial_pose_x: -18.78
    initial_pose_y: 5.14
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: false
    debug_flag: false

graph_based_slam: 
  ros__parameters: 
    ndt_resolution: 3.0
    ndt_num_threads: 1
    voxel_leaf_size: 0.2
    loop_detection_period: 5000
    threshold_loop_closure_score: 0.7
    distance_loop_closure: 100.0
    range_of_searching_loop_closure: 20.0
    search_submap_num: 2
    use_save_map_in_loop: false
    debug_flag: true

