name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  model_viewer_plus: ^1.8.0
  english_words: ^4.0.0
  provider: ^6.0.5
  web_socket_channel: ^2.4.0  # 추가
  fl_chart: ^0.66.2
  http: ^0.13.6
  yaml: ^3.1.1
  yaml_writer: ^1.0.0
  flutter_cube: ^0.1.1
  vector_math: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/axes.obj
    - assets/Boat_.obj
    - assets/xyz_axis.glb
  uses-material-design: true